# Generated by Django 5.1.1 on 2024-09-30 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('min_balance', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('withdrawal_min', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('withdrawal_max', models.DecimalField(decimal_places=2, default=20000, max_digits=10)),
                ('deposit_min', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('deposit_max', models.DecimalField(decimal_places=2, default=100000, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm_app.atm')),
            ],
        ),
    ]
